### PR TITLE
Hotfix/0.2.2.18/refactor path aliases

### PR DESCRIPTION
**Pull request by AdelBeit**
## What type of PR is this? (check all applicable)

- [x] Refactor
- [ ] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description

refactor any instances of relative paths that can instead be turned into path aliases through tsconfig. added a couple of new path aliases in the config as well. 

added an eslint plugin to have path aliases be a part of the linting process, and allows to auto convert them to path aliases using lint --fix

## Related Tickets & Documents

[user story 1](https://projects.digitalaidseattle.org/project-tasks-details?recordId=recOWcAvt4x22gfA8)
[user story 2](https://projects.digitalaidseattle.org/project-tasks-details?recordId=recnZsP22Ahm1dH03)

## QA Instructions, Screenshots, Recordings

The eslint plugin should catch any relative import paths and show an error.

```javascript
// example of code that will produce error:
import foo from "./greet"; // Should use "@/lib"
import bar from "../constants/hello.i18n.js"; // Sould use "@/constants"
```

```javascript
//example of code that won't produce errors
import foo from "@/lib/greet";
import bar from "@/constants/hello.i18n.js";
```

then you can use yarn lint --fix to automatically change those relative paths to aliases

find more info [here](https://github.com/msfragala/eslint-plugin-path-alias)

## Added/updated tests?
_We are aiming for 100% statement coverage._

- [ ] Yes
- [x] No, and this is why: this is code refactoring related to import links and all changes are covered under linting rules 
- [ ] I need help with writing tests

## [optional] Which Seattle Humane animal would you like to dedicate this PR to?

Stanley Yelnats

### CODE REVIEW

**Review by DillonOLeary — APPROVED** [review]
Thanks for cleaning this up. I didn't know that you could do imports like this in TypeScript. Is there some way to add this to linting as well?

**Comment by sharrief** [comment]
> Thanks for cleaning this up. I didn't know that you could do imports like this in TypeScript. Is there some way to add this to linting as well?

Yea @AdelBeit take a look at this plugin which might save you some manual work of updating the files.

https://github.com/msfragala/eslint-plugin-path-alias

**Comment by AdelBeit** [comment]
> > Thanks for cleaning this up. I didn't know that you could do imports like this in TypeScript. Is there some way to add this to linting as well?
> 
> Yea @AdelBeit take a look at this plugin which might save you some manual work of updating the files.
> 
> https://github.com/msfragala/eslint-plugin-path-alias

Nice, I added it as a devdep. thinking of just pushing it to this pr, any objections?

**Review by sharrief — APPROVED** [review]
Approved!

Thanks for taking the initiative to fix these! These relative imports going way up the tree have been an eyesore to me.

nit: I think we can make the imports from siblings (i.e. `./SubComponents.tsx`) allowed. I think the plugin allows for this. But its not a big deal

**Pull request merged**
