### PR TITLE
Feature/4.6.1/new assigned cases

### PR DESCRIPTION
**Pull request by AdelBeit**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [X] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description

pulls new assigned cases for the current logged in user.
 
one thing to discuss is, currently it brings all cases for current user in descending order by creation time. do we need a way to only count new cases that haven't been **opened** yet? if so we will need a way to keep track of what's read and what's not on the tickets.

another point to discuss, currently there are 3 words that refer to the same thing in the codebase; tickets = cases = requests

I wrote the code using 'tickets' but if we can come to a consensus on which to use going forward I'll refactor my code before merging

## Related Tickets & Documents

- Closes [4.6.1.2 UI for New assigned cases](https://projects.digitalaidseattle.org/project-tasks-details?recordId=recxf6F0m1eeRUX0t), [4.6.1.3 New assigned cases backend query](https://projects.digitalaidseattle.org/project-tasks-details?recordId=recYPW5dIq04XoTXu)

## QA Instructions, Screenshots, Recordings

image

### UI accessibility checklist

- [x] Semantic HTML implemented?
- [x] Color contrast tested?

## Added/updated tests?

- [X] Yes
- [ ] No, and this is why: _please replace this line with details on why tests
      have not been included_
- [ ] I need help with writing tests

## [optional] Which Seattle Humane animal would you like to dedicate this PR to?

Stanley Yelnats
alt_text

### CODE REVIEW

**Comment by AdelBeit** [comment]
Need to close #73 first as some code depends on that

**Comment by DillonOLeary** [comment]
> Need to close #73 first as some code depends on that

Closed and merged!

**Comment by DillonOLeary** [comment]
I believe we are using the term "service requests" https://projects.digitalaidseattle.org/project-tasks-details?recordId=rec9ikwws0YwWbylR

**Comment by DillonOLeary** [comment]
talking with Kate about this now. I think there is some ambiguity still, we are going to clarify with Seattle humane. If we can get an answer soon, maybe we can push a change to the PR.

**Comment by sharrief** [comment]
> talking with Kate about this now. I think there is some ambiguity still, we are going to clarify with Seattle humane. If we can get an answer soon, maybe we can push a change to the PR.

Ticket is much easier to write in code. We can change our UI labels but I think we can start to formalize on ticket in the code.

**Comment by DillonOLeary** [comment]
Speaking with Sharrief we discussed changing the way queries are made. More information in slack, but essentially there is not very much information stored in Supabase, so it seems best to just query everything rather than using multiple queries. I think I'll still try to merge this code however, that change would be a larger overhaul

**Comment by sharrief** [comment]
> Speaking with Sharrief we discussed changing the way queries are made. More information in slack, but essentially there is not very much information stored in Supabase, so it seems best to just query everything rather than using multiple queries. I think I'll still try to merge this code however, that change would be a larger overhaul

Yea we can skip the data access changes for now. But @AdelBeit please see if you can address the test changes. You can just remove the tests if trying to get them to render the element is tricky.

**Comment by DillonOLeary** [comment]
> > Speaking with Sharrief we discussed changing the way queries are made. More information in slack, but essentially there is not very much information stored in Supabase, so it seems best to just query everything rather than using multiple queries. I think I'll still try to merge this code however, that change would be a larger overhaul
> 
> Yea we can skip the data access changes for now. But @AdelBeit please see if you can address the test changes. You can just remove the tests if trying to get them to render the element is tricky.

@sharrief are you talking about the test changes in this PR? https://github.com/digitalaidseattle/seattle-humane-app/pull/76

**Comment by sharrief** [comment]
> @sharrief are you talking about the test changes in this PR? https://github.com/digitalaidseattle/seattle-humane-app/pull/76

Yep! But I agree if you find it complex @AdelBeit we can just refactor the tests in a future PR

**Comment by AdelBeit** [comment]
> > @sharrief are you talking about the test changes in this PR? #76
> 
> Yep! But I agree if you find it complex @AdelBeit we can just refactor the tests in a future PR

I'll look at refactoring the tests in this pr before merging

**Comment by AdelBeit** [comment]
ill rebase and refactor this tomorrow now that #76 is merged

**Pull request closed without merging**
