### PR TITLE
features/6.1.3.1/email-notifications

### PR DESCRIPTION
**Pull request by AdelBeit**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [x] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description

Add a route to enable sending emails through resend, this PR doesn't include any code that invokes the email sending functionality, that part will come with the external form PR

## Related Tickets & Documents

- Closes Issue [#6.1.3.1](https://projects.digitalaidseattle.org/project-tasks-details?recordId=recoONnezABIPJE06)

## QA Instructions, Screenshots, Recordings

edit .env.local to include Resend API Key, as well as 'from' and 'to' emails. 
the dev 'from' email is included in the env.local.example file copy it over and make a 'to' email var inside your env.local

you can use postman to test this
make a post request to local:3000/api/notify
here's the curl ( you can paste this in postman directly )
curl --location 'localhost:3000/api/notify' \
--header 'Content-Type: application/json' \
--data '{
    "category": "hi",
    "urgent": "true",
    "createdAt": "10/10/2024"
}'

ask @AdelBeit for resend api key

## Added/updated tests?

- [X] Yes
- [ ] No, and this is why: no UI
- [ ] I need help with writing tests

## Can reviewers merge this PR upon approval?
- [X] yes, reviewers can merge this PR
- [ ] no, the author of this PR needs to merge it

### CODE REVIEW

**Comment by AdelBeit** [comment]
need to discuss where we want to have the email configuration

**Comment by DillonOLeary** [comment]
Got a notification that you requested my review, but it looks like it's still a draft. Let me know when you're ready for reviewers!

**Comment by DillonOLeary** [comment]
I can review it now or after you figure out why the deployment failed, just let me know!

Also I talked to Jeff I'm hoping to have access to Vercel so that we don't need to guess why the deployment fails

**Comment by AdelBeit** [comment]
> I can review it now or after you figure out why the deployment failed, just let me know!
> 
> Also I talked to Jeff I'm hoping to have access to Vercel so that we don't need to guess why the deployment fails

I can run yarn build fine, i dont know why vercel is failing, checked linting as well

**Comment by DillonOLeary** [comment]
This is what I'm seeing:
```
[21:30:51.762] Running build in Washington, D.C., USA (East) – iad1
[21:30:51.876] Cloning github.com/digitalaidseattle/seattle-humane-app (Branch: adelbeit/features/6.1.3.1/email-notifications, Commit: 9bda961)
[21:30:52.252] Cloning completed: 375.93ms
[21:30:56.635] Restored build cache from previous deployment (5tg9kJscrSkeP5kbaEwBZAnBL2Ww)
[21:30:56.708] Running "vercel build"
[21:30:57.127] Vercel CLI 39.0.2
[21:30:57.529] Installing dependencies...
[21:30:57.829] yarn install v1.22.19
[21:30:57.892] [1/4] Resolving packages...
[21:30:57.944] warning Resolution field "string-width@4.2.3" is incompatible with requested version "string-width@^5.1.2"
[21:30:57.944] warning Resolution field "wrap-ansi@7.0.0" is incompatible with requested version "wrap-ansi@^8.1.0"
[21:30:58.158] success Already up-to-date.
[21:30:58.170] Done in 0.34s.
[21:30:58.182] Detected Next.js version: 13.5.6
[21:30:58.185] Running "yarn run build"
[21:30:58.376] yarn run v1.22.19
[21:30:58.402] $ next build
[21:30:59.510]    Linting and checking validity of types ...
[21:31:08.567] 
[21:31:08.567] Failed to compile.
[21:31:08.567] 
[21:31:08.567] ./pages/api/notify.ts
[21:31:08.568] 33:5  Warning: Unexpected console statement.  no-console
[21:31:08.568] 
[21:31:08.568] ./layout/AppFooter.tsx
[21:31:08.568] 12:7  Warning: Using `<img>` could result in slower LCP and higher bandwidth. Consider using `<Image />` from `next/image` to automatically optimize images. This may incur additional usage or cost from your provider. See: https://nextjs.org/docs/messages/no-img-element  @next/next/no-img-element
[21:31:08.568] 
[21:31:08.568] ./layout/AppTopbar.tsx
[21:31:08.568] 39:5  Warning: Unexpected console statement.  no-console
[21:31:08.568] 
[21:31:08.568] ./layout/context/layoutcontext.tsx
[21:31:08.568] 81:7  Warning: React Hook useMemo has missing dependencies: 'layoutConfig', 'layoutState', and 'onMenuToggle'. Either include them or remove the dependency array.  react-hooks/exhaustive-deps
[21:31:08.568] 
[21:31:08.568] ./src/components/ClientDialog.tsx
[21:31:08.568] 87:27  Warning: Unexpected console statement.  no-console
[21:31:08.568] 
[21:31:08.569] ./src/components/email-templates/ServiceRequestNotification.tsx
[21:31:08.569] 15:34  Error: `{' '}` must be placed on a new line  react/jsx-one-expression-per-line
[21:31:08.569] 21:26  Error: `{' '}` must be placed on a new line  react/jsx-one-expression-per-line
[21:31:08.569] 25:20  Error: `{' '}` must be placed on a new line  react/jsx-one-expression-per-line
[21:31:08.569] 
[21:31:08.569] ./src/hooks/useFilters.ts
[21:31:08.569] 55:29  Warning: React Hook useMemo has missing dependencies: 'filterByName', 'filterBySpecies', and 'filterByUrgent'. Either include them or remove the dependency array.  react-hooks/exhaustive-deps
[21:31:08.569] 
[21:31:08.569] info  - Need to disable some ESLint rules? Learn more here: https://nextjs.org/docs/basic-features/eslint#disabling-rules
[21:31:08.599] error Command failed with exit code 1.
[21:31:08.599] info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[21:31:08.705] Error: Command "yarn run build" exited with 1
[21:31:11.852] 
```

**Review by DillonOLeary — APPROVED** [review]
Looks great to me! Just check out the changes I made then feel free to merge it!

**Comment by AdelBeit** [comment]
image

**Comment by AdelBeit** [comment]
--- next steps --- 
code implementation merged, here's what needs to happen to make this fully complete:

1) make resend account and use api key in env variable, resend will need a domain that we own to be connected to it to send emails from that domain, that domain's dns rules need to be configured to allow resend to send email from it

2) edit env vars to reflect correct email addresses

3) email template design and wording

4) the form to trigger the email api route

5) (optional) swap out resend for microsoft exchange

**Pull request merged**
