### PR TITLE
Feature/4.6.1/new assigned cases

### PR DESCRIPTION
**Pull request by AdelBeit**
## What type of PR is this? (check all applicable)

a recreation of #74, git auto closed it for some reason while I was refactoring it. Here we are tests are refactored ready to be merged.

- [ ] Refactor
- [X] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description

pulls new assigned cases for the current logged in user.
 
one thing to discuss is, currently it brings all cases for current user in descending order by creation time. do we need a way to only count new cases that haven't been **opened** yet? if so we will need a way to keep track of what's read and what's not on the tickets.

another point to discuss, currently there are 3 words that refer to the same thing in the codebase; tickets = cases = requests

I wrote the code using 'tickets' but if we can come to a consensus on which to use going forward I'll refactor my code before merging

## Related Tickets & Documents

- Closes [4.6.1.2 UI for New assigned cases](https://projects.digitalaidseattle.org/project-tasks-details?recordId=recxf6F0m1eeRUX0t), [4.6.1.3 New assigned cases backend query](https://projects.digitalaidseattle.org/project-tasks-details?recordId=recYPW5dIq04XoTXu)

## QA Instructions, Screenshots, Recordings

image

### UI accessibility checklist

- [x] Semantic HTML implemented?
- [x] Color contrast tested?

## Added/updated tests?

- [X] Yes
- [ ] No, and this is why: _please replace this line with details on why tests
      have not been included_
- [ ] I need help with writing tests

## [optional] Which Seattle Humane animal would you like to dedicate this PR to?

Stanley Yelnats
alt_text

### CODE REVIEW

**Comment by DillonOLeary** [comment]
I'm getting an error when I run this. I wonder if the problem is that the shared database isn't working as expected. Are you getting the same error?
Screenshot 2024-08-27 at 1 13 21 AM

**Review by DillonOLeary — CHANGES_REQUESTED** [review]
Code looks good, but I'm just wondering if you're seeing the same error I get

**Comment by AdelBeit** [comment]
> Code looks good, but I'm just wondering if you're seeing the same error I get

Bug fix pushed, gonna try and merge with main, just need the necessary supabase migration to be pushed to remote first, can't do it myself 'npx supabase push' requires a password from me for some reason

**Comment by DillonOLeary** [comment]
Ok I'll spend time on this tomorrow. Looks like we also need to generate types again

**Comment by DillonOLeary** [comment]
You should have permission to push the latest changes, but make sure you update supabase first and then run `supabase stop --no-backup` and `supabase start`

**Review by DillonOLeary — APPROVED** [review]
Once you are able to update supabase you can merge this. In the future the supabase update should be a part of our pipeline...

**Pull request merged**
