### PR TITLE
Remove unneeded pages

### PR DESCRIPTION
**Pull request by DillonOLeary**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [x] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description

I removed a few headers from the menu bar. Namely Clients, Animals, and Reports. After speaking with Kate, we both agreed that the information was redundant because it is captured in the other tables on the dashboard. We can add it back if the client specifically requests it.

## QA Instructions, Screenshots, Recordings
Screenshot 2024-11-29 at 11 57 19 PM

### UI accessibility checklist
NA
## Added/updated tests?
_There should be 90% statement coverage and the coverage percent increases with each commit, unless a reviewer approves an exception._

- [x] Yes
- [ ] No, and this is why: _please replace this line with details on why tests
      have not been included_
- [ ] I need help with writing tests

## Can reviewers merge this PR upon approval?
- [x] yes, reviewers can merge this PR
- [ ] no, the author of this PR needs to merge it

## [optional] Are there any post-deployment tasks we need to perform?
NA
## [optional] Which Seattle Humane animal would you like to dedicate this PR to?
Archie
alt_text

### CODE REVIEW

**Comment by AdelBeit** [comment]
hey i see my revert pr mess is in the commit history of this branch and i fear merging without rebasing first might introduce another sprint-6 problem
will you rebase this branch with sprint-9 first before i approve the changes? @DillonOLeary

**Comment by AdelBeit** [comment]
> hey i see my revert pr mess is in the commit history of this branch and i fear merging without rebasing first might introduce another sprint-6 problem will you rebase this branch with sprint-9 first before i approve the changes? @DillonOLeary

confirmed, i copied this branch into my own, then tried to make a pr from that to sprint-9, then tried rebasing that copy onto sprint-9 and then again making a pr and the commit list was just the two 
image

**Comment by DillonOLeary** [comment]
@AdelBeit I can just make this change in my other PR, it's pretty small. That way we can avoid having your changes be a part of it

**Comment by AdelBeit** [comment]
> @AdelBeit I can just make this change in my other PR, it's pretty small. That way we can avoid having your changes be a part of it

Either way make sure you rebase ur branch on top of the branch you're merging into before merging it

**Pull request closed without merging**
